mongo:
  mongouser: username
  mongopass: password
  mongohost: mongo
  mongoport: 27017
  mongodb: chatapp
  usercoll: users
  roomcoll: rooms
  messagecoll: messages

redis:
  host: redis
  password: password
  port: 6379

rabbitmq:
  host: rabbitmq
  user: user
  password: password
  port: 5672
  QueueName: notification

app:
  host: 0.0.0.0
  port: 8002
  debug: true
  secretkey: string
  TokenExpireHour: 2

